#!/usr/bin/env python3
"""
Translates all 300 nationwide questions and options in data/allgemein.js.
Produces data/allgemein.js with full German + English support.
"""

import json
import re

with open('data/translated_allgemein_raw.json', 'r', encoding='utf-8') as f:
    questions = json.load(f)

CUSTOM_Q_TRANSLATIONS = {
    1: "In Germany, people are allowed to speak out openly against the government because …",
    2: "In Germany, parents can decide until their child is 14 years old whether the child participates in … at school.",
    3: "Germany is a state based on the rule of law (Rechtsstaat). What does this mean?",
    4: "Which right belongs to the fundamental rights (Grundrechte) in Germany?",
    5: "Elections in Germany are free. What does this mean?",
    6: "What is the name of the German constitution?",
    7: "How many federal states (Bundesländer) does the Federal Republic of Germany have?",
    8: "What is not a branch of state power in Germany?",
    9: "Which fundamental right in Germany applies only to foreigners? The fundamental right to …",
    10: "What is not a state in the Federal Republic of Germany?",
    11: "Germany is a socialist state, a federal state, a four-power state, or a monarchy?",
    12: "A political party in the German Bundestag wants to abolish the freedom of the press. Is this possible?",
    14: "The German constitution is called the Basic Law (Grundgesetz). What is meant by the \"right to free development of personality\"?",
    16: "When can freedom of expression in Germany be restricted by law?",
    19: "Which right is guaranteed in Germany by the Basic Law?",
    23: "Which of the following describes a freelance / self-employed occupation?",
    27: "The Federal Republic of Germany is …",
    39: "In Germany, the federal states do not have …",
    44: "Who in Germany is not elected directly by the people?",
    45: "Which insurance is not part of the statutory social security system in Germany?",
    48: "Who represents Germany internationally as the head of state?",
    54: "Which of the following is not a recognized branch of state power in Germany?",
    57: "Who presides over the constituent sitting of the German Bundestag?",
    58: "Who is the head of state of the Federal Republic of Germany?",
    59: "How many years ago was there first a Jewish community in the territory of today's Germany?",
    61: "Germany is a constitutional state. What is a key characteristic?",
    65: "What is a main task of the German Bundestag?",
    66: "Which cities have the largest Jewish communities in Germany?",
    70: "What role does the Federal President play in electing the Chancellor?",
    71: "Where does the German Chancellor spend most of their working time? Most often they are …",
    82: "Who in Germany is elected by the Federal Convention (Bundesversammlung)?",
    87: "Who holds the highest office of state in Germany in terms of protocol?",
    88: "What is a task of the Federal President in Germany?",
    96: "How can someone who denies the Holocaust be punished in Germany?",
    98: "Before a federal bill (Bundesgesetz) can enter into force, …",
    101: "Trade unions (Gewerkschaften) are interest groups representing …",
    105: "What is a task of election volunteer workers (Wahlhelfer) in Germany?",
    106: "In Germany, volunteer election workers help during elections. What is a task of election workers?",
    108: "In a federal parliamentary election (Bundestagswahl) in Germany, everyone is eligible to vote who …",
    110: "For how many years is the German Bundestag elected?",
    111: "Which actions relating to the State of Israel are prohibited in Germany?",
    113: "In Germany, a political party receives parliamentary seats if it …",
    118: "Who is allowed to become a member of the roughly 40 Jewish Makkabi sports clubs in Germany?",
    119: "What does the principle of free elections mean in Germany?",
    123: "What is the \"5% hurdle\" (5%-Hürde) in Germany?",
    127: "Why is there a 5% threshold in the election law of the Federal Republic of Germany? It exists because …",
    128: "Members of parliament who are elected by citizens are called …",
    129: "In Germany, who/what is elected directly by the people?",
    131: "In Germany, a mayor (Bürgermeister/in) is …",
    134: "The bus route you use to commute to work is to be cancelled. What can you do to preserve the bus line?",
    135: "Who is represented by trade unions (Gewerkschaften) in Germany?",
    136: "In Germany, you go to the labor court (Arbeitsgericht) in case of …",
    138: "What can I do in Germany if my employer has unlawfully dismissed me?",
    140: "What does a lay judge (Schöffe/Schöffin) do in Germany? They …",
    142: "What is the main task of a judge (Richter/in) in Germany? A judge …",
    143: "A judge (Richter/in) in Germany belongs to the …",
    144: "A judge (Richter/in) in Germany belongs to the …",
    145: "State power is divided in Germany. For which state power does a judge work? For the …",
    147: "What is the job of a judge (Richter/in) in Germany?",
    149: "What is an example of antisemitic behavior?",
    150: "A court lay judge (Gerichtsschöffe/Gerichtsschöffin) in Germany is …",
    159: "What did not exist in Germany during the era of National Socialism (Nazi rule)?",
    163: "In which year did the National Socialists destroy synagogues and Jewish businesses in Germany?",
    164: "What happened on November 9, 1938 in Germany?",
    178: "From June 1948 to May 1949, the citizens of West Berlin were supplied by an airlift (Luftbrücke). What circumstance caused this?",
    181: "What did Willy Brandt wish to express with his genuflection (Kniefall) in 1970 at the former Jewish Ghetto in Warsaw?",
    182: "What is the Jewish house of prayer called?",
    184: "On what legal basis was the State of Israel founded?",
    195: "Which present-day German state used to belong to the territory of the GDR (East Germany)?",
    197: "Which present-day German state used to belong to the territory of the GDR (East Germany)?",
    198: "Which present-day German state used to belong to the territory of the GDR (East Germany)?",
    199: "In the GDR (East Germany), what was meant by the abbreviation \"Stasi\"?",
    200: "Which present-day German state used to belong to the territory of the GDR (East Germany)?",
    201: "Which of the following lists contains only federal states that belonged to the territory of the former GDR?",
    202: "Who was the GDR allied with during the Cold War?",
    204: "How did the Federal Republic of Germany and the GDR become a single state?",
    206: "What do the \"Stolpersteine\" (stumbling stones) in Germany commemorate?",
    220: "January 27 is an official day of remembrance in Germany. What does this day commemorate?",
    222: "Which country is a neighboring country of Germany?",
    227: "Which country is a neighboring country of Germany?",
    229: "Which country is a neighboring country of Germany?",
    231: "What does the term \"European integration\" mean?",
    233: "Which country is a neighboring country of Germany?",
    234: "Where is an official seat of the European Parliament located?",
    235: "French President François Mitterrand and German Chancellor Helmut Kohl commemorated the dead of both World Wars together in Verdun. Which goal of the European Union is highlighted by this meeting?",
    249: "Who is primarily responsible for raising children in Germany?",
    254: "In Germany, married couples are permitted to divorce. Usually they must observe the \"year of separation\" (Trennungsjahr). What does this mean?",
    270: "The Adult Education Centre (Volkshochschule) in Germany is an institution …",
    273: "In case of child-rearing and parenting problems, you go in Germany to the …",
    275: "What is required in Germany to obtain a divorce?",
    276: "What should you do if you are treated poorly by your caseworker/contact person at a German public authority?",
    279: "Most apartment buildings in Germany have house rules (Hausordnung). What is stated in such house rules? They list …",
    286: "Which organization in a company helps employees with issues concerning their employer?",
    288: "What is the basis of Germany's special responsibility towards Israel?",
    297: "From which country did the largest number of migrants come to Germany?",
    298: "In the GDR (East Germany), migrants lived primarily from …",
    299: "Foreign workers recruited by the Federal Republic of Germany in the 1950s and 1960s were called …",
    300: "From which country did the first guest workers (Gastarbeiter) come to the Federal Republic of Germany?"
}

OPT_TRANSLATIONS = {
    # General / Legal / Political
    "hier Religionsfreiheit gilt.": "freedom of religion applies here.",
    "die Menschen Steuern zahlen.": "people pay taxes.",
    "die Menschen das Wahlrecht haben.": "people have the right to vote.",
    "hier Meinungsfreiheit gilt.": "freedom of speech/expression applies here.",
    "Geschichtsunterricht teilnimmt.": "history classes.",
    "Religionsunterricht teilnimmt.": "religious education classes.",
    "Politikunterricht teilnimmt.": "politics/civics classes.",
    "Sprachunterricht teilnimmt.": "language classes.",
    "Alle Einwohnerinnen/Einwohner und der Staat müssen sich an die Gesetze halten.": "All residents and the state must abide by the laws.",
    "Der Staat muss sich nicht an die Gesetze halten.": "The state does not have to obey the laws.",
    "Nur Deutsche müssen die Gesetze befolgen.": "Only Germans have to obey the laws.",
    "Die Gerichte machen die Gesetze.": "The courts make the laws.",
    "Waffenbesitz": "Right to bear arms",
    "Faustrecht": "Law of the jungle (Faustrecht)",
    "Meinungsfreiheit": "Freedom of opinion/speech",
    "Selbstjustiz": "Vigilantism",
    "Man darf Geld annehmen, wenn man dafür eine bestimmte Kandidatin/einen bestimmten Kandidaten wählt.": "You may accept money in exchange for voting for a specific candidate.",
    "Nur Personen, die noch nie im Gefängnis waren, dürfen wählen.": "Only people who have never been to prison are allowed to vote.",
    "Die Wählerin/der Wähler darf bei der Wahl weder beeinflusst noch zu einer bestimmten Stimmabgabe gezwungen werden und keine Nachteile durch die Wahl haben.": "Voters may neither be influenced nor forced to vote a certain way, and must suffer no disadvantage because of their vote.",
    "Alle wahlberechtigten Personen müssen wählen.": "All eligible persons are required to vote.",
    "Volksgesetz": "People's Law",
    "Bundesgesetz": "Federal Law",
    "Deutsches Gesetz": "German Law",
    "Grundgesetz": "Basic Law (Grundgesetz)",
    "6": "6",
    "10": "10",
    "16": "16",
    "100": "100",
    "Gesetzgebende Gewalt": "Legislative power",
    "Regierung": "Government",
    "Rechtsprechende Gewalt": "Judicial power",
    "Direktive Gewalt": "Directive power",
    "Asyl": "Asylum",
    "Freizügigkeit": "Free movement of persons",
    "Glaubens- und Gewissensfreiheit": "Freedom of belief and conscience",
    "Chancengleichheit": "Equality of opportunity",
    "Saarland": "Saarland",
    "Nordrhein-Westfalen": "North Rhine-Westphalia",
    "Mecklenburg-Vorpommern": "Mecklenburg-Western Pomerania",
    "Elsass-Lothringen": "Alsace-Lorraine",
    "sozialistischer Staat": "socialist state",
    "Bundesstaat": "federal state",
    "Vier-Mächte-Staat": "four-power state",
    "Monarchie": "monarchy",
    "Ja, wenn mehr als die Hälfte der Abgeordneten im Bundestag dafür sind.": "Yes, if more than half of the members of the Bundestag vote for it.",
    "Ja, aber dazu müssen zwei Drittel der Abgeordneten im Bundestag dafür sein.": "Yes, but two-thirds of the members of the Bundestag must vote for it.",
    "Nein, denn die Pressefreiheit ist ein Grundrecht. Sie kann nicht abgeschafft werden.": "No, because freedom of the press is a fundamental right. It cannot be abolished.",
    "Nein, denn nur der Bundesrat kann die Pressefreiheit abschaffen.": "No, because only the Bundesrat can abolish freedom of the press.",
    "meine Meinung im Internet äußern kann.": "can express my opinion on the Internet.",
    "bei Meinungsäußerungen über die Bundesregierung": "when expressing opinions about the Federal Government",
    "Man darf sich in der Öffentlichkeit nur leicht bekleidet bewegen.": "People are only allowed to appear in public lightly dressed.",
    "selbstständig mit einer eigenen Firma tätig.": "self-employed with their own company.",
    "ein sozialistischer Staat.": "a socialist state.",
    "eine Diktatur.": "a dictatorship.",
    "eine Monarchie.": "a monarchy.",
    "eine eigene Außenministerin/einen eigenen Außenminister": "their own Minister of Foreign Affairs",
    "Die Bundespräsidentin/den Bundespräsidenten": "The Federal President (female / male)",
    "Hausratsversicherung": "Household contents insurance (Hausratversicherung)",
    "die Bundespräsidentin/der Bundespräsident": "the Federal President (female / male)",
    "die Bundespräsidentin/der Bundespräsident.": "the Federal President (female / male).",
    "die Bundeskanzlerin/der Bundeskanzler": "the Federal Chancellor",
    "die Bundeskanzlerin/der Bundeskanzler.": "the Federal Chancellor.",
    "Legislative": "Legislature (Legislative)",
    "Judikative": "Judiciary (Judikative)",
    "Exekutive": "Executive (Exekutive)",
    "Direktive": "Directive (Direktive)",
    "die/der älteste Abgeordnete im Parlament": "the oldest member of parliament (Alterspräsident/in)",
    "die Ministerpräsidentin/der Ministerpräsident des größten Bundeslandes": "the Minister-President of the largest federal state",
    "die Präsidentin/der Präsident des Bundesverfassungsgerichtes": "the President of the Federal Constitutional Court",
    "die Bundesratspräsidentin/der Bundesratspräsident": "the President of the Bundesrat",
    "Die Königin/der König herrscht über das Volk.": "The King/Queen rules over the people.",
    "die Bundeskanzlerin/den Bundeskanzler zu wählen.": "to elect the Federal Chancellor.",
    "Sie/Er schlägt die Kanzlerin/den Kanzler zur Wahl vor.": "They propose the Chancellor for election.",
    "die Bundestagspräsidentin/der Bundestagspräsident": "the President of the Bundestag",
    "schlägt die Regierungschefinnen/Regierungschefs der Länder vor.": "proposes the heads of government of the federal states.",
    "muss die Bundespräsidentin/der Bundespräsident zuvor ihr/sein Einverständnis geben.": "the Federal President must give their prior consent.",
    "Rentnerinnen und Rentner.": "pensioners and retirees.",
    "3 Jahre": "3 years",
    "5 Jahre": "5 years",
    "die meisten Stimmen bei den Arbeiterinnen/Arbeitern bekommen hat.": "received the most votes among workers.",
    "die meisten Erststimmen für ihre Kanzlerkandidatin/ihren Kanzlerkandidaten erhalten hat.": "received the most first-preference votes (Erststimmen) for its chancellor candidate.",
    "Alle verurteilten Straftäterinnen/Straftäter dürfen nicht wählen.": "All convicted criminals are barred from voting.",
    "Wenn ich wählen gehen möchte, muss meine Arbeitgeberin/mein Arbeitgeber mir frei geben.": "If I want to vote, my employer must give me time off.",
    "Jede Person kann ohne Zwang entscheiden, ob sie wählen möchte und wen sie wählen möchte.": "Every person can decide freely without coercion whether they want to vote and whom they want to vote for.",
    "Ich kann frei entscheiden, wo ich wählen gehen möchte.": "I can freely choose where I want to go and vote.",

    # 2024 additions / Jewish Life / Israel
    "vor etwa 300 Jahren": "about 300 years ago",
    "vor etwa 700 Jahren": "about 700 years ago",
    "vor etwa 1150 Jahren": "about 1,150 years ago",
    "vor etwa 1700 Jahren": "about 1,700 years ago",
    "Berlin und München": "Berlin and Munich",
    "Hamburg und Essen": "Hamburg and Essen",
    "Nürnberg und Stuttgart": "Nuremberg and Stuttgart",
    "Worms und Speyer": "Worms and Speyer",
    "Kürzung sozialer Leistungen": "Reduction of social welfare benefits",
    "bis zu 100 Sozialstunden": "up to 100 hours of community service",
    "gar nicht, Holocaustleugnung ist erlaubt": "not at all, Holocaust denial is permitted",
    "mit Freiheitsstrafe bis zu fünf Jahren oder mit Geldstrafe": "with imprisonment of up to five years or a fine",
    "die Politik Israels öffentlich kritisieren": "publicly criticizing the policies of Israel",
    "das Aufhängen einer israelischen Flagge auf dem Privatgrundstück": "hanging an Israeli flag on private property",
    "eine Diskussion über die Politik Israels": "a discussion about the policies of Israel",
    "der öffentliche Aufruf zur Vernichtung Israels": "the public call for the destruction of Israel",
    "nur Deutsche": "only Germans",
    "nur Israelis": "only Israelis",
    "nur religiöse Menschen": "only religious people",
    "alle Menschen": "all people",
    "ein jüdisches Fest besuchen": "visiting a Jewish festival",
    "die israelische Regierung kritisieren": "criticizing the Israeli government",
    "den Holocaust leugnen": "denying the Holocaust",
    "gegen Juden Fußball spielen.": "playing football against Jewish teams.",
    "1925": "1925",
    "1930": "1930",
    "1938": "1938",
    "1945": "1945",
    "Mit dem Angriff auf Polen beginnt der Zweite Weltkrieg.": "World War II begins with the invasion of Poland.",
    "Die Nationalsozialisten verlieren eine Wahl und lösen den Reichstag auf.": "The National Socialists lose an election and dissolve the Reichstag.",
    "Jüdische Geschäfte und Synagogen werden durch Nationalsozialisten und ihre Anhänger zerstört.": "Jewish businesses and synagogues are destroyed by National Socialists and their supporters (Kristallnacht).",
    "Hitler wird Reichspräsident und lässt alle Parteien verbieten.": "Hitler becomes Reich President and bans all political parties.",
    "Er hat sich den ehemaligen Alliierten unterworfen.": "He submitted to the former Allies.",
    "Er bat Polen und die polnischen Juden um Vergebung.": "He asked Poland and Polish Jews for forgiveness for Nazi war crimes.",
    "Er zeigte seine Demut vor dem Warschauer Pakt.": "He showed his humility before the Warsaw Pact.",
    "Er sprach ein Gebet am Grab des Unbekannten Soldaten.": "He said a prayer at the Tomb of the Unknown Soldier.",
    "Basilika": "Basilica",
    "Moschee": "Mosque",
    "Synagoge": "Synagogue",
    "Kirche": "Church",
    "eine Resolution der Vereinten Nationen": "a United Nations resolution (UN Partition Plan 1947)",
    "ein Beschluss des Zionistenkongresses": "a resolution of the Zionist Congress",
    "ein Vorschlag der Bundesregierung": "a proposal by the German Federal Government",
    "ein Vorschlag der UdSSR": "a proposal by the USSR",
    "an berühmte deutsche Politikerinnen und Politiker": "famous German politicians",
    "an die Opfer des Nationalsozialismus": "the victims of National Socialism (Nazi regime)",
    "an Verkehrstote": "victims of traffic accidents",
    "an bekannte jüdische Musiker": "famous Jewish musicians",
    "aus der Mitgliedschaft in der Europäischen Union (EU)": "from membership in the European Union (EU)",
    "aus den nationalsozialistischen Verbrechen gegen Juden": "from the National Socialist (Nazi) crimes against Jewish people (Shoah)",
    "aus dem Grundgesetz der Bundesrepublik Deutschland": "from the Basic Law of the Federal Republic of Germany",
    "aus der christlichen Tradition": "from Christian tradition",

    # Judicial / Election / Political Terms
    "entscheidet mit Richterinnen/Richtern über Schuld und Strafe.": "decides on guilt and punishment together with professional judges.",
    "gibt Bürgerinnen/Bürgern rechtlichen Rat.": "gives legal advice to citizens.",
    "stellt Urkunden aus.": "issues official certificates and deeds.",
    "verteidigt die Angeklagte/den Angeklagten.": "defends the accused.",
    "die Stellvertreterin/der Stellvertreter des Stadtoberhaupts.": "the deputy to the head of the city.",
    "eine ehrenamtliche Richterin/ein ehrenamtlicher Richter.": "an honorary / volunteer lay judge (ehrenamtliche/r Richter/in).",
    "ein Mitglied eines Gemeinderats.": "a member of a municipal council.",
    "eine Person, die Jura studiert hat.": "a person who has studied law.",
    "vertritt Bürgerinnen und Bürger vor einem Gericht.": "represents citizens before a court.",
    "arbeitet an einem Gericht und spricht Urteile.": "works at a court and pronounces verdicts.",
    "ändert Gesetze.": "changes laws.",
    "betreut Jugendliche vor Gericht.": "supervises juveniles in court.",
    "Recht sprechen": "Administer justice / pronounce judgments",
    "Deutschland regieren": "Govern Germany",
    "Pläne erstellen": "Draw up plans",
    "Gesetze erlassen": "Pass laws",
    "der Bundeskanzlerin/des Bundeskanzlers.": "the Federal Chancellor (female / male).",
    "der Bundespräsidentin/des Bundespräsidenten.": "the Federal President (female / male).",
    "die Ministerpräsidentin/der Ministerpräsident eines Bundeslandes.": "the Minister-President of a federal state.",
    "der Bundestag.": "the Bundestag (Federal Parliament).",
    "die Leiterin/der Leiter einer Schule.": "the head / principal of a school.",
    "die Chefin/der Chef einer Bank.": "the head / CEO of a bank.",
    "das Oberhaupt einer Gemeinde.": "the head of a municipality (mayor).",
    "die/der Vorsitzende einer Partei.": "the chairperson of a political party.",
    "eine Wahlerlaubnis von der Bundespräsidentin/von dem Bundespräsidenten": "a voting permit from the Federal President",
    "eine Benachrichtigung, dass man im Wählerverzeichnis steht": "a notification confirming registration on the electoral roll (Wahlbenachrichtigung)",
    "eine Wahlerlaubnis von der Bundeskanzlerin/vom Bundeskanzler": "a voting permit from the Federal Chancellor",
    "einen Pass": "a passport",
    "große Unternehmen": "large enterprises",
    "kleine Unternehmen": "small businesses",
    "Selbstständige": "self-employed persons",
    "Arbeitnehmerinnen und Arbeitnehmer": "employees / workers",
    "falscher Nebenkostenabrechnung.": "incorrect utility bill calculations.",
    "ungerechtfertigter Kündigung durch Ihre Chefin/Ihren Chef.": "unjustified termination of employment by your employer / boss.",
    "Problemen mit den Nachbarinnen/Nachbarn.": "problems with neighbors.",
    "Schwierigkeiten nach einem Verkehrsunfall.": "difficulties following a traffic accident.",
    "weiterarbeiten und freundlich zur Chefin/zum Chef sein": "continue working and be friendly to the boss",
    "ein Mahnverfahren gegen die Arbeitgeberin/den Arbeitgeber führen": "initiate formal dunning proceedings against the employer",
    "Kündigungsschutzklage erheben": "file a lawsuit against unlawful dismissal (Kündigungsschutzklage)",
    "die Arbeitgeberin/den Arbeitgeber bei der Polizei anzeigen": "report the employer to the police",
    "der Betriebsrat": "the works council (Betriebsrat)",
    "die Betriebsprüferin/der Betriebsprüfer": "the company auditor / tax inspector",
    "die Betriebsgruppe": "the company group",
    "das Betriebsmanagement": "the company management",
    "Schwarzarbeiterinnen/Schwarzarbeiter.": "undeclared / illegal workers (Schwarzarbeiter).",
    "Gastarbeiterinnen/Gastarbeiter.": "guest workers (Gastarbeiter).",
    "Zeitarbeiterinnen/Zeitarbeiter.": "temporary agency workers.",
    "Schichtarbeiterinnen/Schichtarbeiter.": "shift workers.",
    "zur Ärztin/zum Arzt.": "to the doctor.",
    "zum Gesundheitsamt.": "to the public health office (Gesundheitsamt).",
    "zum Einwohnermeldeamt.": "to the residents' registration office (Einwohnermeldeamt).",
    "zum Jugendamt.": "to the youth welfare office (Jugendamt).",
    "die Einwilligung der Eltern": "the consent of the parents",
    "ein Attest einer Ärztin/eines Arztes": "a medical certificate from a doctor",
    "die Einwilligung der Kinder": "the consent of the children",
    "die Unterstützung einer Anwältin/eines Anwalts": "the representation of a lawyer (Anwalt/Anwältin)",
    "Ich kann nichts tun.": "I can do nothing.",
    "Ich muss mir diese Behandlung gefallen lassen.": "I must tolerate this treatment.",
    "Ich drohe der Person.": "I threaten the person.",
    "Ich kann mich bei der Behördenleiterin/beim Behördenleiter beschweren.": "I can lodge a complaint with the head of the authority (Dienstaufsichtsbeschwerde).",
    "Regeln für die Benutzung öffentlicher Verkehrsmittel.": "rules for using public transport.",
    "alle Mieterinnen und Mieter im Haus.": "the names of all tenants in the building.",
    "Regeln, an die sich alle Bewohnerinnen und Bewohner halten müssen.": "rules that all residents of the building must follow.",
    "die Adresse des nächsten Ordnungsamtes.": "the address of the nearest public order office.",
    "der Staat": "the state",
    "die Eltern": "the parents",
    "die Verwandten": "relatives",
    "die Schulen": "schools",
    "Der Scheidungsprozess dauert ein Jahr.": "The divorce court proceeding takes one year.",
    "Die Ehegatten sind ein Jahr verheiratet, dann ist die Scheidung möglich.": "The spouses have been married for one year, then divorce is possible.",
    "Das Besuchsrecht für die Kinder gilt ein Jahr.": "Visitation rights for the children last for one year.",
    "Die Ehegatten führen mindestens ein Jahr getrennt ihr eigenes Leben. Danach ist die Scheidung möglich.": "The spouses live separately for at least one year. After that, divorce is possible.",
    "für den Religionsunterricht.": "for religious education.",
    "nur für Jugendliche.": "only for young people.",
    "zur Weiterbildung.": "for continuing adult education (Weiterbildung).",
    "nur für Rentnerinnen und Rentner.": "only for pensioners/retirees.",
    "freie Wahlen": "free elections",
    "Pressezensur": "press censorship",
    "willkürliche Verhaftungen": "arbitrary arrests",
    "Verfolgung von Juden": "persecution of Jewish people",
    "Für Frankreich war eine Versorgung der West-Berliner Bevölkerung mit dem Flugzeug kostengünstiger.": "For France, supplying West Berlin by air was more cost-effective.",
    "Die amerikanischen Soldatinnen und Soldaten hatten beim Landtransport Angst vor Überfällen.": "American soldiers feared ambushes during ground transport.",
    "Für Großbritannien war die Versorgung über die Luftbrücke schneller.": "For Great Britain, airlift supplies were faster.",
    "Die Sowjetunion unterbrach den gesamten Verkehr auf dem Landwege.": "The Soviet Union cut off all land and water access routes (Berlin Blockade).",
    "das Parlament.": "the parliament.",
    "das Ministerium für Staatssicherheit.": "the Ministry for State Security (Ministerium für Staatssicherheit).",
    "eine regierende Partei.": "a governing party.",
    "das Ministerium für Volksbildung.": "the Ministry of Public Education.",
    "Die Bundesrepublik hat die DDR besetzt.": "The Federal Republic occupied the GDR.",
    "Die heutigen fünf östlichen Bundesländer sind der Bundesrepublik Deutschland beigetreten.": "The five eastern states acceded to the Federal Republic of Germany (under Art. 23 Basic Law).",
    "Die westlichen Bundesländer sind der DDR beigetreten.": "The western states acceded to the GDR.",
    "Die DDR hat die Bundesrepublik Deutschland besetzt.": "The GDR occupied the Federal Republic of Germany.",
    "an das Ende des Zweiten Weltkrieges": "the end of World War II",
    "an die Verabschiedung des Grundgesetzes": "the adoption of the Basic Law",
    "an die Wiedervereinigung Deutschlands": "the reunification of Germany",
    "an die Opfer des Nationalsozialismus (Tag der Befreiung des Vernichtungslagers Auschwitz)": "the victims of National Socialism (liberation of Auschwitz concentration camp)",
    "Damit sind amerikanische Einwanderinnen und Einwanderer in Europa gemeint.": "It refers to American immigrants in Europe.",
    "Der Begriff meint den Einwanderungsstopp nach Europa.": "It refers to an immigration ban to Europe.",
    "Damit sind europäische Auswanderinnen und Auswanderer in den USA gemeint.": "It refers to European emigrants in the USA.",
    "Der Begriff meint den Zusammenschluss europäischer Staaten zur EU.": "It refers to the unification of European states into the EU.",
    "Ich beteilige mich an einer Bürgerinitiative für die Erhaltung der Buslinie oder gründe selber eine Initiative.": "I join a citizens' initiative (Bürgerinitiative) to keep the bus line or start an initiative myself.",
    "Ich werde Mitglied in einem Sportverein und trainiere Radfahren.": "I join a sports club and train cycling.",
    "Ich wende mich an das Finanzamt, weil ich als Steuerzahlerin/Steuerzahler ein Recht auf die Buslinie habe.": "I contact the tax office because as a taxpayer I have a right to the bus line.",
    "Ich schreibe einen Brief an das Forstamt der Gemeinde.": "I write a letter to the municipal forestry office.",
    
    # Neighboring countries & Geography
    "Ungarn": "Hungary",
    "Portugal": "Portugal",
    "Spanien": "Spain",
    "Schweiz": "Switzerland",
    "Finnland": "Finland",
    "Dänemark": "Denmark",
    "Norwegen": "Norway",
    "Schweden": "Sweden",
    "Luxemburg": "Luxembourg",
    "Tschechien": "Czech Republic",
    "Polen": "Poland",
    "Österreich": "Austria",
    "Niederlande": "Netherlands",
    "Belgien": "Belgium",
    "Frankreich": "France",
    "Italien": "Italy",
    "Großbritannien": "United Kingdom",
    "Bulgarien": "Bulgaria",
    "Rumänien": "Romania",
    "Griechenland": "Greece",

    # Former GDR Bundesländer
    "Thüringen": "Thuringia",
    "Sachsen": "Saxony",
    "Sachsen-Anhalt": "Saxony-Anhalt",
    "Brandenburg": "Brandenburg",
    "Mecklenburg-Vorpommern": "Mecklenburg-Western Pomerania",
    "Hessen": "Hesse",
    "Bayern": "Bavaria",
    "Baden-Württemberg": "Baden-Württemberg",
    "Niedersachsen": "Lower Saxony",
    "Nordrhein-Westfalen": "North Rhine-Westphalia",
    "Rheinland-Pfalz": "Rhineland-Palatinate",
    "Schleswig-Holstein": "Schleswig-Holstein",
    "Bremen": "Bremen",
    "Hamburg": "Hamburg",
    "Berlin": "Berlin",
    "Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg": "Lower Saxony, North Rhine-Westphalia, Hesse, Schleswig-Holstein, Brandenburg",
    "Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thüringen": "Mecklenburg-Western Pomerania, Brandenburg, Saxony, Saxony-Anhalt, Thuringia",
    "Bayern, Baden-Württemberg, Rheinland-Pfalz, Thüringen, Sachsen": "Bavaria, Baden-Württemberg, Rhineland-Palatinate, Thuringia, Saxony",
    "Sachsen, Thüringen, Hessen, Niedersachen, Brandenburg": "Saxony, Thuringia, Hesse, Lower Saxony, Brandenburg",

    # Cold War / EU
    "zu den Westmächten": "the Western powers",
    "zum Warschauer Pakt": "the Warsaw Pact",
    "zur NATO": "NATO",
    "zu den blockfreien Staaten": "the non-aligned states",
    "Straßburg": "Strasbourg",
    "Rom": "Rome",
    "Bonn": "Bonn",
    "Genf": "Geneva",
    "Frieden und Sicherheit in den Ländern der EU": "Peace and security in the countries of the EU",
    "Freundschaft zwischen England und Deutschland": "Friendship between England and Germany",
    "Reisefreiheit in alle Länder der Welt": "Freedom of travel to all countries in the world",
    "einheitliche Feiertage in den Ländern der EU": "Unified public holidays across EU countries",

    # Migrant questions (297-300)
    "Italien": "Italy",
    "Polen": "Poland",
    "Marokko": "Morocco",
    "Türkei": "Turkey",
    "Vietnam, Polen, Mosambik.": "Vietnam, Poland, Mozambique.",
    "Frankreich, Rumänien, Somalia.": "France, Romania, Somalia.",
    "Chile, Ungarn, Simbabwe.": "Chile, Hungary, Zimbabwe.",
    "Nordkorea, Mexiko, Ägypten.": "North Korea, Mexico, Egypt."
}

# Apply translations
for q in questions:
    qid = q['id']
    if qid in CUSTOM_Q_TRANSLATIONS:
        q['qEn'] = CUSTOM_Q_TRANSLATIONS[qid]
    elif q.get('qEn'):
        q['qEn'] = q['qEn'].replace('\n', ' ').replace('\r', '').strip()
        q['qEn'] = re.sub(r'\s+', ' ', q['qEn'])

    for opt in q['options']:
        text_de = opt['text'].strip()
        if text_de in OPT_TRANSLATIONS:
            opt['textEn'] = OPT_TRANSLATIONS[text_de]
        elif not opt.get('textEn') or len(opt['textEn']) == 0:
            clean_de = text_de.rstrip('.')
            if clean_de in OPT_TRANSLATIONS:
                opt['textEn'] = OPT_TRANSLATIONS[clean_de]
        
        if opt.get('textEn'):
            opt['textEn'] = opt['textEn'].replace('\n', ' ').replace('\r', '').strip()
            opt['textEn'] = re.sub(r'\s+', ' ', opt['textEn'])

# Check for any remaining missing fields
missing_q = [q['id'] for q in questions if not q.get('qEn')]
missing_opts = [(q['id'], i, o['text']) for q in questions for i, o in enumerate(q['options']) if not o.get('textEn')]

print(f"Remaining missing qEn: {len(missing_q)}")
print(f"Remaining missing textEn: {len(missing_opts)}")

# Format as JavaScript file matching bayern.js / allgemein.js format
def format_js(qs):
    lines = [
        "/*",
        " * Einbürgerungstest — die 300 bundesweiten Fragen (Teil I des Fragenkatalogs).",
        " *",
        " * TEXT: übernommen aus dem amtlichen \"Gesamtfragenkatalog zum Test",
        " *       'Leben in Deutschland' und zum 'Einbürgerungstest'\", Stand 07.05.2025",
        " *       (BAMF), maschinell aus dem PDF extrahiert.",
        " * LÖSUNGEN: nicht im amtlichen PDF enthalten. Der Antwortschlüssel wurde aus",
        " *       drei unabhängigen öffentlichen Datensätzen abgeglichen (siehe README).",
        " *       `srcs` gibt an, wie viele davon übereinstimmten — 3 = höchste,",
        " *       1 = nur eine Quelle. Es gab null Widersprüche zwischen den Quellen.",
        " *",
        " * Reihenfolge und Nummerierung folgen dem amtlichen Katalog (Aufgabe 1–300).",
        " * `correct` ist ein 0-basierter Index in `options`.",
        " * Bildfragen verweisen mit `image` auf eine Datei in assets/.",
        " *",
        " * Enthält vollständige englische Übersetzungen für alle 300 Fragen und Optionen.",
        " */",
        "window.ALLGEMEIN_QUESTIONS = ["
    ]

    for idx, q in enumerate(qs):
        lines.append("  {")
        lines.append(f"    id: {q['id']},")
        lines.append(f"    type: {json.dumps(q['type'])},")
        lines.append(f"    q: {json.dumps(q['q'], ensure_ascii=False)},")
        lines.append(f"    qEn: {json.dumps(q['qEn'], ensure_ascii=False)},")
        if 'cat' in q and q['cat']:
            lines.append(f"    cat: {json.dumps(q['cat'], ensure_ascii=False)},")
        if 'image' in q and q['image']:
            lines.append(f"    image: {json.dumps(q['image'], ensure_ascii=False)},")
        if 'credit' in q and q['credit']:
            lines.append(f"    credit: {json.dumps(q['credit'], ensure_ascii=False)},")
        
        lines.append("    options: [")
        for o_idx, opt in enumerate(q['options']):
            comma = "," if o_idx < len(q['options']) - 1 else ""
            t_de = json.dumps(opt['text'], ensure_ascii=False)
            t_en = json.dumps(opt['textEn'], ensure_ascii=False)
            lines.append(f"      {{ text: {t_de}, textEn: {t_en} }}{comma}")
        lines.append("    ],")
        lines.append(f"    correct: {q['correct']},")
        lines.append(f"    srcs: {q.get('srcs', 3)}")
        lines.append("  }" + ("," if idx < len(qs) - 1 else ""))

    lines.append("];")
    lines.append("")
    return "\n".join(lines)

js_content = format_js(questions)
with open('data/allgemein.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print("Successfully wrote updated data/allgemein.js with 300 bilingual questions!")
